services:
  backend:
    build:
      context: ../fullstack-api
    ports:
      - "4000:4000"
    volumes:
      - ../fullstack-api:/usr/src/app
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    depends_on:
      - db

  frontend:
    build:
      context: ../fullstack-app
    ports:
      - "3000:3000"
    volumes:
      - ../fullstack-app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
