name: Deploy api to Fly.io

on:
  push:
    paths:
      - fullstack-api/**
    branches:
      - main  # Specifies that this workflow runs on pushes to the main branch
      - ci-cd  # todo: remove

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest  # Specifies the runner environment
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checks out your repository under $GITHUB_WORKSPACE

    - name: setup flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: fly deploy
      run: cd fullstack-api && flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_API }}
